#!/bin/bash

numTransfer="80"
count="0"
for pod in $(kubectl get pods -l k8s-app="xrootd-server-gc" --output=jsonpath={.items..metadata.name});
do
    kubectl exec $pod -- bash /home/makeFile $count $numTransfer &
    count=$[$count+$numTransfer]
done
