#!/bin/bash

# Args: 1 NumStreams, 2 Source, 3 Dest, 4 NumTransfers
function HTTPTransfer {
    curl -L -X COPY \
    -H "Overwrite: T" \
    -H "X-Number-Of-Streams: $1" \
    -H "Source: http://$2:1094/testFile" \
    http://$3:1094/testDestFile$4
}

# Args: 1 Protocol, 2 NumStreams, 3 Source, 4 Dest, 5 NumTransfers
function doTransfer {
    PID=()
    for i in $(seq 1 $4)
    do
        HTTPTransfer $1 $2 $3 $i & PID[$i]=$!
    done;
    for i in $(seq 1 $4)
    do
        wait ${PID[$i]};
    done;
}

doTransfer $1 $2 $3 $4
