#!/bin/bash

head -c 1073741824 </dev/urandom > /mnt/ramdisk/mainFile
for i in $(seq $1 $[$1+$2-1])
do
    #dd if=/dev/zero of=/mnt/ramdisk/testSourceFile$i bs=256M count=$3
    ln /mnt/ramdisk/mainFile /mnt/ramdisk/testSourceFile$i
done;
